name: MongoSK
version: '${version}'
author: Romitou
description: A Skript addon to interact with MongoDB.
main: fr.romitou.mongosk.MongoSK
website: https://github.com/Romitou/MongoSK
api-version: 1.13
depend:
  - Skript
