blank_issues_enabled: false
contact_links:
  - name: 💬 Discord server
    url: https://discord.com/invite/6jeQkRcMkk
    about: Our Discord server is the perfect place if you want to get quick help from the community and contributors.
  - name: 📰 GitHub Discussions
    url: https://github.com/Romitou/MongoSK/discussions
    about: Although this space is more formal, you can still ask questions, communicate on GitHub discussions.
