name: Build & Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Gradle
        run: ./gradlew clean shadowJar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MongoSK
          path: build/libs/**

  test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        skript-version: [2.11.0, 2.11.1, 2.11.2, 2.12.0, 2.12.1, 2.12.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: MongoSK
          path: build/libs

      - name: Run tests with Skript ${{ matrix.skript-version }}
        uses: SkriptLang/skript-test-action@v1.2
        with:
          test_script_directory: src/test/resources
          skript_repo_ref: ${{ matrix.skript-version }}
          extra_plugins_directory: build/libs
          run_vanilla_tests: false
